import './globals.css'
import Nav from '@/components/Navigation'

export const metadata = {
  title: 'Finance-Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
      {children}
      </body>
    </html>
  )
}
